from app.planner.models import Plan
from app.tools.models import ToolCall, ToolResult
from app.tools.registry import tool_registry


class Executor:
    """
    Executes plans generated by the planner.

    If a plan requires a tool, it is converted into a
    ToolCall and executed through the Tool Registry.
    """

    def execute(
        self,
        plan: Plan,
    ) -> ToolResult:

        if not plan.use_tool:
            return ToolResult(
                success=False,
                output="No tool execution required.",
            )

        call = ToolCall(
            name=plan.tool_name,
            arguments=plan.arguments,
        )

        return tool_registry.execute(call)


executor = Executor()
