from pathlib import Path

from app.planner.models import Plan


class Planner:
    """
    Rule-based planner (v0.3).

    Later this will be replaced by an LLM planner.
    """

    def plan(
        self,
        query: str,
    ) -> Plan:

        lower = query.lower()

        # List directory
        if "list" in lower and "directory" in lower:
            return Plan(
                use_tool=True,
                tool_name="list_directory",
                arguments={
                    "path": str(Path.cwd()),
                },
                reasoning="Directory listing requested.",
            )

        # Read file
        if "read" in lower and "file" in lower:
            return Plan(
                use_tool=True,
                tool_name="read_file",
                arguments={
                    "path": "README.md",
                },
                reasoning="File reading requested.",
            )

        # Write file
        if "write" in lower and "file" in lower:
            return Plan(
                use_tool=True,
                tool_name="write_file",
                arguments={
                    "path": "output.txt",
                    "content": "Generated by JARVIS",
                },
                reasoning="File writing requested.",
            )

        # Search files
        if "find" in lower or "search" in lower:
            return Plan(
                use_tool=True,
                tool_name="search_files",
                arguments={
                    "path": str(Path.cwd()),
                    "pattern": query,
                },
                reasoning="Searching project files.",
            )

        # Default to LLM
        return Plan(
            use_tool=False,
            reasoning="LLM response only.",
        )


planner = Planner()
